src/Entity/Intendente.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IntendenteRepository")
 */
class Intendente
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estado;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_inicio;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fin_Funcion;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Persona", inversedBy="intendente", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $relation;



     public function __toString()
    {
        #$nombreApellido= 
       
        return  $this-> getEstado();

        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getFechaInicio(): ?\DateTimeInterface
    {
        return $this->fecha_inicio;
    }

    public function setFechaInicio(\DateTimeInterface $fecha_inicio): self
    {
        $this->fecha_inicio = $fecha_inicio;

        return $this;
    }

    public function getFinFuncion(): ?\DateTimeInterface
    {
        return $this->fin_Funcion;
    }

    public function setFinFuncion(?\DateTimeInterface $fin_Funcion): self
    {
        $this->fin_Funcion = $fin_Funcion;

        return $this;
    }

    public function getRelation(): ?Persona
    {
        return $this->relation;
    }

    public function setRelation(Persona $relation): self
    {
        $this->relation = $relation;

        return $this;
    }
}

src/Form/IntendenteType.php
<?php

namespace App\Form;

use App\Entity\Intendente;
use App\Entity\Persona;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IntendenteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('estado')
            ->add('fecha_inicio', DateType::class, [
                'widget'     => 'single_text',
                'empty_data' => '',

                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5'      => false,
                // adds a class that can be selected in JavaScript
                'attr'       => ['class' => 'js-datepicker'],
                'format'     => 'dd/mm/yyyy',

            ])

            ->add('fin_Funcion', DateType::class, [
                'widget'   => 'single_text',
                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5'    => false,
                // adds a class that can be selected in JavaScript
                'attr'     => ['class' => 'js-datepicker'],
                'format'   => 'dd/mm/yyyy',
                'required' => false,

            ])
            //->add('fin_Funcion')
            //https://symfony.com/doc/current/reference/forms/types/date.html
            ->add('relation', EntityType::class, [
                'class'        => Persona::class,
                'choice_label' => 'dni', //'nombre',
                'label'        => 'DNI Intendente',
                'placeholder'  => 'Selecciona el DNI del Intendente',

            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Intendente::class,
        ]);
    }
}

src/Controller/BaseController.php
<?php
namespace App\Controller;

use App\Entity\Persona;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

abstract class BaseController extends AbstractController
{
    protected function getUser(): Persona
    {
        return parent::getUser();
    }
}

src/Controller/IntendenteController.php
<?php

namespace App\Controller;

use App\Entity\Intendente;
use App\Form\IntendenteType;
use App\Repository\IntendenteRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/intendente")
 * @IsGranted("ROLE_USER")
 */
class IntendenteController extends AbstractController
{
    /**
     * @Route("/", name="intendente_index", methods={"GET"})
     */
    public function index(IntendenteRepository $intendenteRepository): Response
    {
        return $this->render('intendente/index.html.twig', [
            'intendentes' => $intendenteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="intendente_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    function new (Request $request): Response{
        /*==================================================
        =            permisos sobre controllers            =
        ==================================================*/

        // $this->denyAccessUnlessGranted('ROLE_ADMIN');

        /*=====  End of permisos sobre controllers  ======*/

        $intendente = new Intendente();
        $form       = $this->createForm(IntendenteType::class, $intendente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /*==============================================================================================================================================
            =            aca seguro tengo que hacer una funcion
            para detectar si el intendente ya tiene cargado el DNI            =
            ==============================================================================================================================================*/

            /*=====  End of aca seguro tengo que hacer una funcion   ======*/

            // dd($form->getdata());
            $persona = $intendente->getRelation();
            //dd(   $persona-> getId() );
            //

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($intendente);
            $entityManager->flush();

            return $this->redirectToRoute('persona_new', ['persona' => $persona->getId()]);
            /*mio*/
            /*
             */
            // return $this->redirectToRoute('intendente_index');
        }

        return $this->render('intendente/new.html.twig', [
            'intendente' => $intendente,
            'form'       => $form->createView(),
        ]);
        die();
    }

    /**
     * @Route("/news", name="intendente_news", methods={"GET","POST"})
     */
    public function news(Request $request): Response
    {
        $intendente = new Intendente();
        $form       = $this->createForm(IntendenteType::class, $intendente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /*==============================================================================================================================================
            =            aca seguro tengo que hacer una funcion
            para detectar si el intendente ya tiene cargado el DNI            =
            ==============================================================================================================================================*/

            /*=====  End of aca seguro tengo que hacer una funcion   ======*/

            // dd($form->getdata());
            $persona = $intendente->getRelation();
            //dd(   $persona-> getId() );
            //

            return $this->redirectToRoute('persona_new', ['persona' => $persona->getId()]);
            /*mio*/
            /*    $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($intendente);
            $entityManager->flush();
             */
            // return $this->redirectToRoute('intendente_index');
        }

        return $this->render('intendente/news.html.twig', [
            'intendente' => $intendente,
            'form'       => $form->createView(),
        ]);
        die();
    }

    /**
     * @Route("/{id}", name="intendente_show", methods={"GET"})
     */
    public function show(Intendente $intendente): Response
    {

        $persona = $intendente->getRelation();
        /* dump($persona->getDni());
        dump($persona->getNombre());
        dump($persona->getApellido());*/

        //die();
        return $this->render('intendente/show.html.twig', [
            'intendente' => $intendente,
            'persona'    => $persona,
        ]);
        //die();
    }

    /**
     * @Route("/{id}/edit", name="intendente_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Intendente $intendente): Response
    {
        //dd($intendente);
        $form = $this->createForm(IntendenteType::class, $intendente);
        $form->handleRequest($request);
        //dd($intendente-> getId() );
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('intendente_index');
        }

        return $this->render('intendente/edit.html.twig', [
            'intendente' => $intendente,
            'form'       => $form->createView(),
        ]);
        die();
    }

    /**
     * @Route("/{id}", name="intendente_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Intendente $intendente): Response
    {
        if ($this->isCsrfTokenValid('delete' . $intendente->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($intendente);
            $entityManager->flush();
        }

        return $this->redirectToRoute('intendente_index');
        die();
    }
}

templates/intendente/_delete_form.html.twig
<form method="post" action="{{ path('intendente_delete', {'id': intendente.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ intendente.id) }}">
    <button class="btn">Delete</button>
</form>

templates/intendente/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}

    <button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}
 

templates/intendente/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Intendente{% endblock %}

{% block body %}
    <h1>Edit Intendente</h1>

    {{ include('intendente/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('intendente_index') }}">back to list</a>

    {{ include('intendente/_delete_form.html.twig') }}
{% endblock %}

templates/intendente/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intendente index{% endblock %}

{% block body %}
    <h1>Intendente index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Estado</th>
                <th>Fecha_inicio</th>
                <th>Fin_Funcion</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for intendente in intendentes %}
            <tr>
                <td>{{ intendente.id }}</td>
                <td>{{ intendente.estado }}</td>
                <td>{{ intendente.fechaInicio ? intendente.fechaInicio|date('Y-m-d') : '' }}</td>
                <td>{{ intendente.finFuncion ? intendente.finFuncion|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('intendente_show', {'id': intendente.id}) }}">show</a>
                    <a href="{{ path('intendente_edit', {'id': intendente.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('intendente_new') }}">Create new</a>
   

{% endblock %}

templates/intendente/new.html.twig
{% extends 'base.html.twig' %}


{% block javascripts %}
  {{parent()}}
  
 <script src="{{asset('js/bootstrap-datepicker.min.js')}}"></script> 
 <script src="{{asset('locales/bootstrap-datepicker.es.min.js')}}"></script> 


 <script>
    $(document).ready(function() {
        // you may need to change this code if you are not using Bootstrap Datepicker
       /* $('.js-datepicker').datepicker({
            format: 'yyyy-mm-dd'
        });
   */
       
          $('.js-datepicker').datepicker({
        language: "es",
        autoclose: true,
        todayHighlight: true
    });

       /* $('.js-datepicker').datepicker({
        language: "es",
        keyboardNavigation: false,
        autoclose: true,
        todayHighlight: true,
        beforeShowDay: function(date){
              if (date.getMonth() == (new Date()).getMonth())
                switch (date.getDate()){
                  case 4:
                    return {
                      tooltip: 'Example tooltip',
                      classes: 'active'
                    };
                  case 8:
                    return false;
                  case 12:
                    return "green";
              }
            }
    });*/
         });
</script>
{% endblock javascripts %}

  
{% block stylesheets %}

	{{parent()}}
<link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap-datepicker.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/bootstrap-datepicker.min.css')}}">
{% endblock %}




{% block title %}New Intendente{% endblock %}



{% block body %}
	

	<p>Username: {{ app.user.username ?? 'Anonymous user' }}</p>
{% if app.debug %}
    <p>Request method: {{ app.request.method }}</p>
    <p>Application Environment: {{ app.environment }}</p>
{% endif %}


    <h1>Create new Intendente</h1>

    {{ include('intendente/_form.html.twig') }}

    <a href="{{ path('intendente_index') }}">back to list</a>
{% endblock %}

templates/intendente/news.html.twig
{% extends 'base.html.twig' %}




{% block title %}New Intendente{% endblock %}

{% block body %}
	

	<p>Username: {{ app.user.username ?? 'Anonymous user' }}</p>
{% if app.debug %}
    <p>Request method: {{ app.request.method }}</p>
    <p>Application Environment: {{ app.environment }}</p>
{% endif %}


    <h1>Create new Intendente</h1>

    {{ include('intendente/_form.html.twig') }}

    <a href="{{ path('intendente_index') }}">back to list</a>
{% endblock %}

templates/intendente/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intendente{% endblock %}

{% block body %}

    <h1>Intendente</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ intendente.id }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ intendente.estado }}</td>
            </tr>
            <tr>
                <th>Fecha_inicio</th>
                <td>{{ intendente.fechaInicio ? intendente.fechaInicio|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fin_Funcion</th>
                <td>{{ intendente.finFuncion ? intendente.finFuncion|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <button type="submit" class="btn btn-primary">Delete</button>

      

    <a href="{{ path('intendente_index') }}">back to list</a>

    <a href="{{ path('intendente_edit', {'id': intendente.id}) }}">edit</a>

    {{ include('intendente/_delete_form.html.twig') }}

    <h1 class="text-center" data-toggle="tooltip" data-placement="bottom" title="js de bootstrap funcionando :)" >Hola <s>Acceseo</s> acceseo!</h1>

    {% block javascripts %}
       

 


 <script src="{{ asset('js/pepe.js') }}"></script>


    {% endblock %}


     <table class="table">
        <tbody>
            <tr>
                <th>Id_Persona</th>
                <td>{{ persona.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ persona.nombre }}</td>
            </tr>
            <tr>
                <th>Apellido</th>
                <td>{{ persona.apellido }}</td>
            </tr>

            <tr>
                <th>DNI</th>
                <td>{{ persona.dni }}</td>
            </tr>
            
        </tbody>
    </table>
{% endblock %}


   